### ISSUE TITLE
Link mismatch in slides

### ISSUE THREAD

**Issue by tachyons** [redpanthers/slides#54]
Currently vim editor slides link gives the slide of "Art of debugging"

[Link ](https://redpanthers.io/slides/vim-editor-tips/#/)

**Comment by manusajith** [comment]
@tachyons thanks for reporting this. Checking.

**Comment by tachyons** [comment]
see [this](https://github.com/redpanthers/slides/commit/7b223d16605b8ca22d2a719278b088ced9b08ba1) commit , permlink is 'vim-editor-tips' . It seems that this route overrides original route

**Comment by sibinx7** [comment]
Update permalink in 'Art of Debugging' file 
#55
